### PR TITLE
Fix issues with running Globe and add README

### PR DESCRIPTION
**Pull request by ohnx**
Bugfixes:
 * Bug: Globe does not treat directories in the locale folder correctly (i.e. it loops infinitely until a segfault).
**FIX: Remove the translations in `old/` and move the translations in `new/` to parent directory**
 * Bug: Globe does not know where to find required program data files if the files are not in the expected location
**FIX: Create script to place image icons in expected directory**

Other notes:
 * Change default language to English
 * Tested as (mostly) working on x86_64 and x86_gcc2
 * Add README with screenshot of application

### CODE REVIEW

**Comment by diversys** [comment]
I built Globe recipe using your commit but it doesn't display toolbar icons:

image

**Comment by ohnx** [comment]
@diversys Are you running it after `make install`?

If the icons + localization aren't in `~/config/settings/Globe`, they won't be loaded correctly. This appears to be a hardcoded search location (see [here](https://github.com/HaikuArchives/Globe/blob/master/src/RHTML_options.cpp#L51)).

`make install` copies the right files to the right places.

**Comment by diversys** [comment]
Ah, no. I'm building globe recipe with haikuporter. hardcoded search path needs to be changed then as resources do not belong to settings in anyway .

**Comment by ohnx** [comment]
Where should I put it in instead?

**Comment by diversys** [comment]
Next to Globe binary.

**Pull request merged**
